version: '3.9'
services:
    machine2:
        build: 'machine'
        restart: always
        networks:
            - machine_network
    machine1:
        build: 'machine'
        restart: always
        networks:
            - machine_network
        command: bash -c "rm -f ~/.ssh/id_rsa; ssh-keygen -q -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''; echo 'test123' | sshpass ssh-copy-id -o 'StrictHostKeyChecking no' -i ~/.ssh/id_rsa root@machine2; /usr/sbin/sshd -D"
        depends_on:
          - machine2
    machine_launch:
        build: 'machine_launch'
        restart: always
        networks:
            - machine_network
        command: bash -c "rm -f ~/.ssh/id_rsa; ssh-keygen -q -t rsa -b 4096 -f ~/.ssh/id_rsa -N ''; echo 'test123' | sshpass ssh-copy-id -o 'StrictHostKeyChecking no' -i ~/.ssh/id_rsa root@machine1; bash"
        depends_on:
          - machine1
        tty: true
networks:
  machine_network:
    name: machine_network
    driver: bridge

